language: c
compiler:
  - gcc
script: make test
before_install:
    - script/bootstrap.sh
    - cd src
notifications:
  hipchat:
    - secure: "Qi99dMt+44DuIdcvkgps4V/SFbot5Sew7Jz1wkDKSzbTPDZsV2cPyRCdqKMD\nOmb1/2Q9Zyud1RYEUNvNWLpP2WspeM7bfO5ZboM3qh+wh16/pOECM4+RMAeQ\nsOAoBFMwqlzK9lgG3CgBhL+VpsWltf/Kd5/E4bft4g6E16vQQjQ="
