language: c
sudo: false
cache:
  directories:
  - dependencies
compiler:
  - clang
script: PLATFORM=TESTING make test_long
install:
   - gem install coveralls-lcov
before_install:
    - script/bootstrap.sh
    - cd src
after_success:
    - PLATFORM=TESTING make coverage
    - coveralls-lcov build/tests/coverage.info
