language: c
sudo: false
addons:
  apt:
    packages:
      - libc6:i386
      - libgd2-xpm
      - ia32-libs
      - ia32-libs-multiarch
cache:
  apt: true
  directories:
  - dependencies
compiler:
  - clang
script: PLATFORM=TESTING make test_long
install:
   - gem install coveralls-lcov
before_install:
    - script/bootstrap.sh
    - cd src
after_success:
    - PLATFORM=TESTING make coverage
    - coveralls-lcov build/tests/coverage.info
